      

package com.usion.common.persistence.info;

/**
 * <p>Title: Information of table: usion_berth</p>
 * <p>Description:  Data Information Object </p>
 * <p>Copyright: Copyright (c) 2015</p>
 * <p>Company: USION </p>
 * <p>Generation Time: 2015-10-28 12:37:48 </p>
 *  Do NOT change this file by hand.
 *  This java source file is generated by JAF_ORM .
 *  tableinfo.vm version timestamp: 2015-10-28 08:30:00
 *
 * @author Administrator
 */

public class UsionBerthInfo
{
	/**
	 * table name of dto
	 */
	public static String TABLENAME = "usion_berth";
	
	/**
	 * column ID
	 */
	public static String ID ="ID";
	/**
	 * column BERTHCODE
	 */
	public static String BERTHCODE ="BERTHCODE";
	/**
	 * column PROVINCECODE
	 */
	public static String PROVINCECODE ="PROVINCECODE";
	/**
	 * column CITYCODE
	 */
	public static String CITYCODE ="CITYCODE";
	/**
	 * column ZONECODE
	 */
	public static String ZONECODE ="ZONECODE";
	/**
	 * column AREANAME
	 */
	public static String AREANAME ="AREANAME";
	/**
	 * column BUSINESSAREANAME
	 */
	public static String BUSINESSAREANAME ="BUSINESSAREANAME";
	/**
	 * column PARKNAME
	 */
	public static String PARKNAME ="PARKNAME";
	/**
	 * column INUSEFLAG
	 */
	public static String INUSEFLAG ="INUSEFLAG";
	/**
	 * column BERTHTYPE
	 */
	public static String BERTHTYPE ="BERTHTYPE";
	/**
	 * column ENTERPRISEINFO
	 */
	public static String ENTERPRISEINFO ="ENTERPRISEINFO";
	/**
	 * column LNGINFO
	 */
	public static String LNGINFO ="LNGINFO";
	/**
	 * column LATINFO
	 */
	public static String LATINFO ="LATINFO";
	/**
	 * column ACTIVEDATE
	 */
	public static String ACTIVEDATE ="ACTIVEDATE";
	/**
	 * column CLOSEDATE
	 */
	public static String CLOSEDATE ="CLOSEDATE";
	/**
	 * column STATUS
	 */
	public static String STATUS ="STATUS";
	/**
	 * column CREATETIME
	 */
	public static String CREATETIME ="CREATETIME";
	/**
	 * column UPDATETIME
	 */
	public static String UPDATETIME ="UPDATETIME";
	/**
	 * @return String table name of dto
	 */
	public static String getTableName() {
		return TABLENAME;
	}
	
	/**
    *  Columns
    */
    public static String[] columnNames(){
        String[] columnNames = new String[18];        
        columnNames[0]="ID";
        columnNames[1]="BERTHCODE";
        columnNames[2]="PROVINCECODE";
        columnNames[3]="CITYCODE";
        columnNames[4]="ZONECODE";
        columnNames[5]="AREANAME";
        columnNames[6]="BUSINESSAREANAME";
        columnNames[7]="PARKNAME";
        columnNames[8]="INUSEFLAG";
        columnNames[9]="BERTHTYPE";
        columnNames[10]="ENTERPRISEINFO";
        columnNames[11]="LNGINFO";
        columnNames[12]="LATINFO";
        columnNames[13]="ACTIVEDATE";
        columnNames[14]="CLOSEDATE";
        columnNames[15]="STATUS";
        columnNames[16]="CREATETIME";
        columnNames[17]="UPDATETIME";
        return columnNames;     
    }
	/******************************************************
	*
	*  Get Column Name
	*
	*******************************************************/
	/**
	 * Getter ID, PK , NOT NULL   	 
	 */
	public static String columnId(){
		 return ID;
	}
	/**
	 * Getter BERTHCODE   	 
	 */
	public static String columnBerthcode(){
		 return BERTHCODE;
	}
	/**
	 * Getter PROVINCECODE   	 
	 */
	public static String columnProvincecode(){
		 return PROVINCECODE;
	}
	/**
	 * Getter CITYCODE   	 
	 */
	public static String columnCitycode(){
		 return CITYCODE;
	}
	/**
	 * Getter ZONECODE   	 
	 */
	public static String columnZonecode(){
		 return ZONECODE;
	}
	/**
	 * Getter AREANAME   	 
	 */
	public static String columnAreaname(){
		 return AREANAME;
	}
	/**
	 * Getter BUSINESSAREANAME   	 
	 */
	public static String columnBusinessareaname(){
		 return BUSINESSAREANAME;
	}
	/**
	 * Getter PARKNAME   	 
	 */
	public static String columnParkname(){
		 return PARKNAME;
	}
	/**
	 * Getter INUSEFLAG , NOT NULL   	 
	 */
	public static String columnInuseflag(){
		 return INUSEFLAG;
	}
	/**
	 * Getter BERTHTYPE   	 
	 */
	public static String columnBerthtype(){
		 return BERTHTYPE;
	}
	/**
	 * Getter ENTERPRISEINFO   	 
	 */
	public static String columnEnterpriseinfo(){
		 return ENTERPRISEINFO;
	}
	/**
	 * Getter LNGINFO   	 
	 */
	public static String columnLnginfo(){
		 return LNGINFO;
	}
	/**
	 * Getter LATINFO   	 
	 */
	public static String columnLatinfo(){
		 return LATINFO;
	}
	/**
	 * Getter ACTIVEDATE   	 
	 */
	public static String columnActivedate(){
		 return ACTIVEDATE;
	}
	/**
	 * Getter CLOSEDATE   	 
	 */
	public static String columnClosedate(){
		 return CLOSEDATE;
	}
	/**
	 * Getter STATUS   	 
	 */
	public static String columnStatus(){
		 return STATUS;
	}
	/**
	 * Getter CREATETIME , NOT NULL   	 
	 */
	public static String columnCreatetime(){
		 return CREATETIME;
	}
	/**
	 * Getter UPDATETIME , NOT NULL   	 
	 */
	public static String columnUpdatetime(){
		 return UPDATETIME;
	}
	/******************************************************
	*
	*  Get Column Java Type
	*
	*******************************************************/
	/**
	 * Getter ID, PK , NOT NULL   	 
	 */
	public static String columnJavaTypeId(){
		 return "String";
	}
	/**
	 * Getter BERTHCODE   	 
	 */
	public static String columnJavaTypeBerthcode(){
		 return "String";
	}
	/**
	 * Getter PROVINCECODE   	 
	 */
	public static String columnJavaTypeProvincecode(){
		 return "String";
	}
	/**
	 * Getter CITYCODE   	 
	 */
	public static String columnJavaTypeCitycode(){
		 return "String";
	}
	/**
	 * Getter ZONECODE   	 
	 */
	public static String columnJavaTypeZonecode(){
		 return "String";
	}
	/**
	 * Getter AREANAME   	 
	 */
	public static String columnJavaTypeAreaname(){
		 return "String";
	}
	/**
	 * Getter BUSINESSAREANAME   	 
	 */
	public static String columnJavaTypeBusinessareaname(){
		 return "String";
	}
	/**
	 * Getter PARKNAME   	 
	 */
	public static String columnJavaTypeParkname(){
		 return "String";
	}
	/**
	 * Getter INUSEFLAG , NOT NULL   	 
	 */
	public static String columnJavaTypeInuseflag(){
		 return "String";
	}
	/**
	 * Getter BERTHTYPE   	 
	 */
	public static String columnJavaTypeBerthtype(){
		 return "String";
	}
	/**
	 * Getter ENTERPRISEINFO   	 
	 */
	public static String columnJavaTypeEnterpriseinfo(){
		 return "String";
	}
	/**
	 * Getter LNGINFO   	 
	 */
	public static String columnJavaTypeLnginfo(){
		 return "String";
	}
	/**
	 * Getter LATINFO   	 
	 */
	public static String columnJavaTypeLatinfo(){
		 return "String";
	}
	/**
	 * Getter ACTIVEDATE   	 
	 */
	public static String columnJavaTypeActivedate(){
		 return "Date";
	}
	/**
	 * Getter CLOSEDATE   	 
	 */
	public static String columnJavaTypeClosedate(){
		 return "Date";
	}
	/**
	 * Getter STATUS   	 
	 */
	public static String columnJavaTypeStatus(){
		 return "String";
	}
	/**
	 * Getter CREATETIME , NOT NULL   	 
	 */
	public static String columnJavaTypeCreatetime(){
		 return "Timestamp";
	}
	/**
	 * Getter UPDATETIME , NOT NULL   	 
	 */
	public static String columnJavaTypeUpdatetime(){
		 return "Timestamp";
	}
	/******************************************************
	*
	*  Get Column Database Type
	*
	*******************************************************/
	/**
	 * Getter ID, PK , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeId(){
		 return "VARCHAR";
	}
	/**
	 * Getter BERTHCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeBerthcode(){
		 return "VARCHAR";
	}
	/**
	 * Getter PROVINCECODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeProvincecode(){
		 return "VARCHAR";
	}
	/**
	 * Getter CITYCODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeCitycode(){
		 return "VARCHAR";
	}
	/**
	 * Getter ZONECODE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeZonecode(){
		 return "VARCHAR";
	}
	/**
	 * Getter AREANAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeAreaname(){
		 return "VARCHAR";
	}
	/**
	 * Getter BUSINESSAREANAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeBusinessareaname(){
		 return "VARCHAR";
	}
	/**
	 * Getter PARKNAME   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeParkname(){
		 return "VARCHAR";
	}
	/**
	 * Getter INUSEFLAG , NOT NULL   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeInuseflag(){
		 return "VARCHAR";
	}
	/**
	 * Getter BERTHTYPE   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeBerthtype(){
		 return "VARCHAR";
	}
	/**
	 * Getter ENTERPRISEINFO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeEnterpriseinfo(){
		 return "VARCHAR";
	}
	/**
	 * Getter LNGINFO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeLnginfo(){
		 return "VARCHAR";
	}
	/**
	 * Getter LATINFO   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeLatinfo(){
		 return "VARCHAR";
	}
	/**
	 * Getter ACTIVEDATE   	 
	 * columnType is DATE
	 */
	public static String columnDatabaseTypeActivedate(){
		 return "DATE";
	}
	/**
	 * Getter CLOSEDATE   	 
	 * columnType is DATE
	 */
	public static String columnDatabaseTypeClosedate(){
		 return "DATE";
	}
	/**
	 * Getter STATUS   	 
	 * columnType is VARCHAR
	 */
	public static String columnDatabaseTypeStatus(){
		 return "VARCHAR";
	}
	/**
	 * Getter CREATETIME , NOT NULL   	 
	 * columnType is TIMESTAMP
	 */
	public static String columnDatabaseTypeCreatetime(){
		 return "TIMESTAMP";
	}
	/**
	 * Getter UPDATETIME , NOT NULL   	 
	 * columnType is TIMESTAMP
	 */
	public static String columnDatabaseTypeUpdatetime(){
		 return "TIMESTAMP";
	}
	/******************************************************
	*
	*  Get Column Width
	*
	*******************************************************/
	/**
	 * Column Width
	 */
	public static int columnWidthId(){
		 return 35;
	}
		/**
	 * Column Width
	 */
	public static int columnWidthBerthcode(){
		 return 35;
	}
		/**
	 * Column Width
	 */
	public static int columnWidthProvincecode(){
		 return 32;
	}
		/**
	 * Column Width
	 */
	public static int columnWidthCitycode(){
		 return 32;
	}
		/**
	 * Column Width
	 */
	public static int columnWidthZonecode(){
		 return 32;
	}
		/**
	 * Column Width
	 */
	public static int columnWidthAreaname(){
		 return 128;
	}
		/**
	 * Column Width
	 */
	public static int columnWidthBusinessareaname(){
		 return 128;
	}
		/**
	 * Column Width
	 */
	public static int columnWidthParkname(){
		 return 128;
	}
		/**
	 * Column Width
	 */
	public static int columnWidthInuseflag(){
		 return 1;
	}
		/**
	 * Column Width
	 */
	public static int columnWidthBerthtype(){
		 return 4;
	}
		/**
	 * Column Width
	 */
	public static int columnWidthEnterpriseinfo(){
		 return 128;
	}
		/**
	 * Column Width
	 */
	public static int columnWidthLnginfo(){
		 return 32;
	}
		/**
	 * Column Width
	 */
	public static int columnWidthLatinfo(){
		 return 32;
	}
		/**
	 * Column Width
	 */
	public static int columnWidthStatus(){
		 return 2;
	}
	}